### PR TITLE
handles keyboard interrupt

### PR DESCRIPTION
**Pull request by dberenbaum**
Related to #2

### CODE REVIEW

**Review by pmrowla — APPROVED** [review]

**Comment by dberenbaum** [comment]
@pmrowla There's actually a bunch of these that need to get merged unfortunately (one for each branch)! Might need to consider a better way to manage this repo.

**Review by pmrowla — APPROVED** [review]

**Comment by pmrowla** [comment]
@dberenbaum maybe better to just organize this into a single repo/branch with directories containing the different types of pipeline examples?

**Comment by pmrowla** [comment]
then the docs/examples could just show the usage for both
```
cd live
# run `dvc.yaml` from current working dir
dvc exp run
```
and
```
# run a specific target
dvc exp run live/dvc.yaml
```

**Comment by dberenbaum** [comment]
Yeah, that's a good idea, but I'm not sure if it's good to introduce more concepts like that or keep it as simple as possible.

More importantly, I don't think `dvc exp show` is well-equipped for this kind of setup. If someone tries out multiple directories, they will get different columns for each, and the metric names will get long, which will just make it hard to read the table (at least I think so, I haven't tested it out with this example).

**Pull request merged**
